/*
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package overseerr

import (
	"encoding/json"
)

// GetStatusAppdata200Response struct for GetStatusAppdata200Response
type GetStatusAppdata200Response struct {
	AppData *bool `json:"appData,omitempty"`
	AppDataPath *string `json:"appDataPath,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetStatusAppdata200Response GetStatusAppdata200Response

// NewGetStatusAppdata200Response instantiates a new GetStatusAppdata200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStatusAppdata200Response() *GetStatusAppdata200Response {
	this := GetStatusAppdata200Response{}
	return &this
}

// NewGetStatusAppdata200ResponseWithDefaults instantiates a new GetStatusAppdata200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStatusAppdata200ResponseWithDefaults() *GetStatusAppdata200Response {
	this := GetStatusAppdata200Response{}
	return &this
}

// GetAppData returns the AppData field value if set, zero value otherwise.
func (o *GetStatusAppdata200Response) GetAppData() bool {
	if o == nil || isNil(o.AppData) {
		var ret bool
		return ret
	}
	return *o.AppData
}

// GetAppDataOk returns a tuple with the AppData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStatusAppdata200Response) GetAppDataOk() (*bool, bool) {
	if o == nil || isNil(o.AppData) {
    return nil, false
	}
	return o.AppData, true
}

// HasAppData returns a boolean if a field has been set.
func (o *GetStatusAppdata200Response) HasAppData() bool {
	if o != nil && !isNil(o.AppData) {
		return true
	}

	return false
}

// SetAppData gets a reference to the given bool and assigns it to the AppData field.
func (o *GetStatusAppdata200Response) SetAppData(v bool) {
	o.AppData = &v
}

// GetAppDataPath returns the AppDataPath field value if set, zero value otherwise.
func (o *GetStatusAppdata200Response) GetAppDataPath() string {
	if o == nil || isNil(o.AppDataPath) {
		var ret string
		return ret
	}
	return *o.AppDataPath
}

// GetAppDataPathOk returns a tuple with the AppDataPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStatusAppdata200Response) GetAppDataPathOk() (*string, bool) {
	if o == nil || isNil(o.AppDataPath) {
    return nil, false
	}
	return o.AppDataPath, true
}

// HasAppDataPath returns a boolean if a field has been set.
func (o *GetStatusAppdata200Response) HasAppDataPath() bool {
	if o != nil && !isNil(o.AppDataPath) {
		return true
	}

	return false
}

// SetAppDataPath gets a reference to the given string and assigns it to the AppDataPath field.
func (o *GetStatusAppdata200Response) SetAppDataPath(v string) {
	o.AppDataPath = &v
}

func (o GetStatusAppdata200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AppData) {
		toSerialize["appData"] = o.AppData
	}
	if !isNil(o.AppDataPath) {
		toSerialize["appDataPath"] = o.AppDataPath
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *GetStatusAppdata200Response) UnmarshalJSON(bytes []byte) (err error) {
	varGetStatusAppdata200Response := _GetStatusAppdata200Response{}

	if err = json.Unmarshal(bytes, &varGetStatusAppdata200Response); err == nil {
		*o = GetStatusAppdata200Response(varGetStatusAppdata200Response)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "appData")
		delete(additionalProperties, "appDataPath")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetStatusAppdata200Response struct {
	value *GetStatusAppdata200Response
	isSet bool
}

func (v NullableGetStatusAppdata200Response) Get() *GetStatusAppdata200Response {
	return v.value
}

func (v *NullableGetStatusAppdata200Response) Set(val *GetStatusAppdata200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStatusAppdata200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStatusAppdata200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStatusAppdata200Response(val *GetStatusAppdata200Response) *NullableGetStatusAppdata200Response {
	return &NullableGetStatusAppdata200Response{value: val, isSet: true}
}

func (v NullableGetStatusAppdata200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStatusAppdata200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


