/*
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 

API version: v1.33.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package overseerr

import (
	"encoding/json"
)

// checks if the TestRadarr2XXResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestRadarr2XXResponse{}

// TestRadarr2XXResponse struct for TestRadarr2XXResponse
type TestRadarr2XXResponse struct {
	Profiles []ServiceProfile `json:"profiles,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TestRadarr2XXResponse TestRadarr2XXResponse

// NewTestRadarr2XXResponse instantiates a new TestRadarr2XXResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestRadarr2XXResponse() *TestRadarr2XXResponse {
	this := TestRadarr2XXResponse{}
	return &this
}

// NewTestRadarr2XXResponseWithDefaults instantiates a new TestRadarr2XXResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestRadarr2XXResponseWithDefaults() *TestRadarr2XXResponse {
	this := TestRadarr2XXResponse{}
	return &this
}

// GetProfiles returns the Profiles field value if set, zero value otherwise.
func (o *TestRadarr2XXResponse) GetProfiles() []ServiceProfile {
	if o == nil || IsNil(o.Profiles) {
		var ret []ServiceProfile
		return ret
	}
	return o.Profiles
}

// GetProfilesOk returns a tuple with the Profiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRadarr2XXResponse) GetProfilesOk() ([]ServiceProfile, bool) {
	if o == nil || IsNil(o.Profiles) {
		return nil, false
	}
	return o.Profiles, true
}

// HasProfiles returns a boolean if a field has been set.
func (o *TestRadarr2XXResponse) HasProfiles() bool {
	if o != nil && !IsNil(o.Profiles) {
		return true
	}

	return false
}

// SetProfiles gets a reference to the given []ServiceProfile and assigns it to the Profiles field.
func (o *TestRadarr2XXResponse) SetProfiles(v []ServiceProfile) {
	o.Profiles = v
}

func (o TestRadarr2XXResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestRadarr2XXResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Profiles) {
		toSerialize["profiles"] = o.Profiles
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TestRadarr2XXResponse) UnmarshalJSON(data []byte) (err error) {
	varTestRadarr2XXResponse := _TestRadarr2XXResponse{}

	err = json.Unmarshal(data, &varTestRadarr2XXResponse)

	if err != nil {
		return err
	}

	*o = TestRadarr2XXResponse(varTestRadarr2XXResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "profiles")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTestRadarr2XXResponse struct {
	value *TestRadarr2XXResponse
	isSet bool
}

func (v NullableTestRadarr2XXResponse) Get() *TestRadarr2XXResponse {
	return v.value
}

func (v *NullableTestRadarr2XXResponse) Set(val *TestRadarr2XXResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTestRadarr2XXResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTestRadarr2XXResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestRadarr2XXResponse(val *TestRadarr2XXResponse) *NullableTestRadarr2XXResponse {
	return &NullableTestRadarr2XXResponse{value: val, isSet: true}
}

func (v NullableTestRadarr2XXResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestRadarr2XXResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


