/*
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 

API version: v1.33.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package overseerr

import (
	"encoding/json"
	"fmt"
)

// TestSonarrRequest struct for TestSonarrRequest
type TestSonarrRequest struct {
	Hostname string `json:"hostname"`
	Port float32 `json:"port"`
	ApiKey string `json:"apiKey"`
	UseSsl bool `json:"useSsl"`
	BaseUrl *string `json:"baseUrl,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TestSonarrRequest TestSonarrRequest

// NewTestSonarrRequest instantiates a new TestSonarrRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestSonarrRequest(hostname string, port float32, apiKey string, useSsl bool) *TestSonarrRequest {
	this := TestSonarrRequest{}
	this.Hostname = hostname
	this.Port = port
	this.ApiKey = apiKey
	this.UseSsl = useSsl
	return &this
}

// NewTestSonarrRequestWithDefaults instantiates a new TestSonarrRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestSonarrRequestWithDefaults() *TestSonarrRequest {
	this := TestSonarrRequest{}
	return &this
}

// GetHostname returns the Hostname field value
func (o *TestSonarrRequest) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *TestSonarrRequest) GetHostnameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *TestSonarrRequest) SetHostname(v string) {
	o.Hostname = v
}

// GetPort returns the Port field value
func (o *TestSonarrRequest) GetPort() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *TestSonarrRequest) GetPortOk() (*float32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *TestSonarrRequest) SetPort(v float32) {
	o.Port = v
}

// GetApiKey returns the ApiKey field value
func (o *TestSonarrRequest) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *TestSonarrRequest) GetApiKeyOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *TestSonarrRequest) SetApiKey(v string) {
	o.ApiKey = v
}

// GetUseSsl returns the UseSsl field value
func (o *TestSonarrRequest) GetUseSsl() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.UseSsl
}

// GetUseSslOk returns a tuple with the UseSsl field value
// and a boolean to check if the value has been set.
func (o *TestSonarrRequest) GetUseSslOk() (*bool, bool) {
	if o == nil {
    return nil, false
	}
	return &o.UseSsl, true
}

// SetUseSsl sets field value
func (o *TestSonarrRequest) SetUseSsl(v bool) {
	o.UseSsl = v
}

// GetBaseUrl returns the BaseUrl field value if set, zero value otherwise.
func (o *TestSonarrRequest) GetBaseUrl() string {
	if o == nil || isNil(o.BaseUrl) {
		var ret string
		return ret
	}
	return *o.BaseUrl
}

// GetBaseUrlOk returns a tuple with the BaseUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestSonarrRequest) GetBaseUrlOk() (*string, bool) {
	if o == nil || isNil(o.BaseUrl) {
    return nil, false
	}
	return o.BaseUrl, true
}

// HasBaseUrl returns a boolean if a field has been set.
func (o *TestSonarrRequest) HasBaseUrl() bool {
	if o != nil && !isNil(o.BaseUrl) {
		return true
	}

	return false
}

// SetBaseUrl gets a reference to the given string and assigns it to the BaseUrl field.
func (o *TestSonarrRequest) SetBaseUrl(v string) {
	o.BaseUrl = &v
}

func (o TestSonarrRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["hostname"] = o.Hostname
	}
	if true {
		toSerialize["port"] = o.Port
	}
	if true {
		toSerialize["apiKey"] = o.ApiKey
	}
	if true {
		toSerialize["useSsl"] = o.UseSsl
	}
	if !isNil(o.BaseUrl) {
		toSerialize["baseUrl"] = o.BaseUrl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *TestSonarrRequest) UnmarshalJSON(bytes []byte) (err error) {
	varTestSonarrRequest := _TestSonarrRequest{}

	if err = json.Unmarshal(bytes, &varTestSonarrRequest); err == nil {
		*o = TestSonarrRequest(varTestSonarrRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "hostname")
		delete(additionalProperties, "port")
		delete(additionalProperties, "apiKey")
		delete(additionalProperties, "useSsl")
		delete(additionalProperties, "baseUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTestSonarrRequest struct {
	value *TestSonarrRequest
	isSet bool
}

func (v NullableTestSonarrRequest) Get() *TestSonarrRequest {
	return v.value
}

func (v *NullableTestSonarrRequest) Set(val *TestSonarrRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTestSonarrRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTestSonarrRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestSonarrRequest(val *TestSonarrRequest) *NullableTestSonarrRequest {
	return &NullableTestSonarrRequest{value: val, isSet: true}
}

func (v NullableTestSonarrRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestSonarrRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


