/*
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 

API version: v1.33.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package overseerr

import (
	"encoding/json"
)

// checks if the GetUserWatchData2XXResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUserWatchData2XXResponse{}

// GetUserWatchData2XXResponse struct for GetUserWatchData2XXResponse
type GetUserWatchData2XXResponse struct {
	RecentlyWatched []MediaInfo `json:"recentlyWatched,omitempty"`
	PlayCount *float32 `json:"playCount,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetUserWatchData2XXResponse GetUserWatchData2XXResponse

// NewGetUserWatchData2XXResponse instantiates a new GetUserWatchData2XXResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserWatchData2XXResponse() *GetUserWatchData2XXResponse {
	this := GetUserWatchData2XXResponse{}
	return &this
}

// NewGetUserWatchData2XXResponseWithDefaults instantiates a new GetUserWatchData2XXResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserWatchData2XXResponseWithDefaults() *GetUserWatchData2XXResponse {
	this := GetUserWatchData2XXResponse{}
	return &this
}

// GetRecentlyWatched returns the RecentlyWatched field value if set, zero value otherwise.
func (o *GetUserWatchData2XXResponse) GetRecentlyWatched() []MediaInfo {
	if o == nil || IsNil(o.RecentlyWatched) {
		var ret []MediaInfo
		return ret
	}
	return o.RecentlyWatched
}

// GetRecentlyWatchedOk returns a tuple with the RecentlyWatched field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserWatchData2XXResponse) GetRecentlyWatchedOk() ([]MediaInfo, bool) {
	if o == nil || IsNil(o.RecentlyWatched) {
		return nil, false
	}
	return o.RecentlyWatched, true
}

// HasRecentlyWatched returns a boolean if a field has been set.
func (o *GetUserWatchData2XXResponse) HasRecentlyWatched() bool {
	if o != nil && !IsNil(o.RecentlyWatched) {
		return true
	}

	return false
}

// SetRecentlyWatched gets a reference to the given []MediaInfo and assigns it to the RecentlyWatched field.
func (o *GetUserWatchData2XXResponse) SetRecentlyWatched(v []MediaInfo) {
	o.RecentlyWatched = v
}

// GetPlayCount returns the PlayCount field value if set, zero value otherwise.
func (o *GetUserWatchData2XXResponse) GetPlayCount() float32 {
	if o == nil || IsNil(o.PlayCount) {
		var ret float32
		return ret
	}
	return *o.PlayCount
}

// GetPlayCountOk returns a tuple with the PlayCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserWatchData2XXResponse) GetPlayCountOk() (*float32, bool) {
	if o == nil || IsNil(o.PlayCount) {
		return nil, false
	}
	return o.PlayCount, true
}

// HasPlayCount returns a boolean if a field has been set.
func (o *GetUserWatchData2XXResponse) HasPlayCount() bool {
	if o != nil && !IsNil(o.PlayCount) {
		return true
	}

	return false
}

// SetPlayCount gets a reference to the given float32 and assigns it to the PlayCount field.
func (o *GetUserWatchData2XXResponse) SetPlayCount(v float32) {
	o.PlayCount = &v
}

func (o GetUserWatchData2XXResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUserWatchData2XXResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RecentlyWatched) {
		toSerialize["recentlyWatched"] = o.RecentlyWatched
	}
	if !IsNil(o.PlayCount) {
		toSerialize["playCount"] = o.PlayCount
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetUserWatchData2XXResponse) UnmarshalJSON(data []byte) (err error) {
	varGetUserWatchData2XXResponse := _GetUserWatchData2XXResponse{}

	err = json.Unmarshal(data, &varGetUserWatchData2XXResponse)

	if err != nil {
		return err
	}

	*o = GetUserWatchData2XXResponse(varGetUserWatchData2XXResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "recentlyWatched")
		delete(additionalProperties, "playCount")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetUserWatchData2XXResponse struct {
	value *GetUserWatchData2XXResponse
	isSet bool
}

func (v NullableGetUserWatchData2XXResponse) Get() *GetUserWatchData2XXResponse {
	return v.value
}

func (v *NullableGetUserWatchData2XXResponse) Set(val *GetUserWatchData2XXResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserWatchData2XXResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserWatchData2XXResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserWatchData2XXResponse(val *GetUserWatchData2XXResponse) *NullableGetUserWatchData2XXResponse {
	return &NullableGetUserWatchData2XXResponse{value: val, isSet: true}
}

func (v NullableGetUserWatchData2XXResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserWatchData2XXResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


