/*
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 

API version: v1.35.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package overseerr

import (
	"encoding/json"
)

// checks if the GetMovieRatingscombined2XXResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMovieRatingscombined2XXResponse{}

// GetMovieRatingscombined2XXResponse struct for GetMovieRatingscombined2XXResponse
type GetMovieRatingscombined2XXResponse struct {
	Rt *GetMovieRatings2XXResponse `json:"rt,omitempty"`
	Imdb *GetMovieRatingscombined2XXResponseImdb `json:"imdb,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetMovieRatingscombined2XXResponse GetMovieRatingscombined2XXResponse

// NewGetMovieRatingscombined2XXResponse instantiates a new GetMovieRatingscombined2XXResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMovieRatingscombined2XXResponse() *GetMovieRatingscombined2XXResponse {
	this := GetMovieRatingscombined2XXResponse{}
	return &this
}

// NewGetMovieRatingscombined2XXResponseWithDefaults instantiates a new GetMovieRatingscombined2XXResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMovieRatingscombined2XXResponseWithDefaults() *GetMovieRatingscombined2XXResponse {
	this := GetMovieRatingscombined2XXResponse{}
	return &this
}

// GetRt returns the Rt field value if set, zero value otherwise.
func (o *GetMovieRatingscombined2XXResponse) GetRt() GetMovieRatings2XXResponse {
	if o == nil || IsNil(o.Rt) {
		var ret GetMovieRatings2XXResponse
		return ret
	}
	return *o.Rt
}

// GetRtOk returns a tuple with the Rt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMovieRatingscombined2XXResponse) GetRtOk() (*GetMovieRatings2XXResponse, bool) {
	if o == nil || IsNil(o.Rt) {
		return nil, false
	}
	return o.Rt, true
}

// HasRt returns a boolean if a field has been set.
func (o *GetMovieRatingscombined2XXResponse) HasRt() bool {
	if o != nil && !IsNil(o.Rt) {
		return true
	}

	return false
}

// SetRt gets a reference to the given GetMovieRatings2XXResponse and assigns it to the Rt field.
func (o *GetMovieRatingscombined2XXResponse) SetRt(v GetMovieRatings2XXResponse) {
	o.Rt = &v
}

// GetImdb returns the Imdb field value if set, zero value otherwise.
func (o *GetMovieRatingscombined2XXResponse) GetImdb() GetMovieRatingscombined2XXResponseImdb {
	if o == nil || IsNil(o.Imdb) {
		var ret GetMovieRatingscombined2XXResponseImdb
		return ret
	}
	return *o.Imdb
}

// GetImdbOk returns a tuple with the Imdb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMovieRatingscombined2XXResponse) GetImdbOk() (*GetMovieRatingscombined2XXResponseImdb, bool) {
	if o == nil || IsNil(o.Imdb) {
		return nil, false
	}
	return o.Imdb, true
}

// HasImdb returns a boolean if a field has been set.
func (o *GetMovieRatingscombined2XXResponse) HasImdb() bool {
	if o != nil && !IsNil(o.Imdb) {
		return true
	}

	return false
}

// SetImdb gets a reference to the given GetMovieRatingscombined2XXResponseImdb and assigns it to the Imdb field.
func (o *GetMovieRatingscombined2XXResponse) SetImdb(v GetMovieRatingscombined2XXResponseImdb) {
	o.Imdb = &v
}

func (o GetMovieRatingscombined2XXResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMovieRatingscombined2XXResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rt) {
		toSerialize["rt"] = o.Rt
	}
	if !IsNil(o.Imdb) {
		toSerialize["imdb"] = o.Imdb
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetMovieRatingscombined2XXResponse) UnmarshalJSON(data []byte) (err error) {
	varGetMovieRatingscombined2XXResponse := _GetMovieRatingscombined2XXResponse{}

	err = json.Unmarshal(data, &varGetMovieRatingscombined2XXResponse)

	if err != nil {
		return err
	}

	*o = GetMovieRatingscombined2XXResponse(varGetMovieRatingscombined2XXResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "rt")
		delete(additionalProperties, "imdb")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetMovieRatingscombined2XXResponse struct {
	value *GetMovieRatingscombined2XXResponse
	isSet bool
}

func (v NullableGetMovieRatingscombined2XXResponse) Get() *GetMovieRatingscombined2XXResponse {
	return v.value
}

func (v *NullableGetMovieRatingscombined2XXResponse) Set(val *GetMovieRatingscombined2XXResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMovieRatingscombined2XXResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMovieRatingscombined2XXResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMovieRatingscombined2XXResponse(val *GetMovieRatingscombined2XXResponse) *NullableGetMovieRatingscombined2XXResponse {
	return &NullableGetMovieRatingscombined2XXResponse{value: val, isSet: true}
}

func (v NullableGetMovieRatingscombined2XXResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMovieRatingscombined2XXResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


