/*
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 

API version: v1.34.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package overseerr

import (
	"encoding/json"
)

// checks if the GetPlexSync2XXResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPlexSync2XXResponse{}

// GetPlexSync2XXResponse struct for GetPlexSync2XXResponse
type GetPlexSync2XXResponse struct {
	Running *bool `json:"running,omitempty"`
	Progress *float32 `json:"progress,omitempty"`
	Total *float32 `json:"total,omitempty"`
	CurrentLibrary *PlexLibrary `json:"currentLibrary,omitempty"`
	Libraries []PlexLibrary `json:"libraries,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetPlexSync2XXResponse GetPlexSync2XXResponse

// NewGetPlexSync2XXResponse instantiates a new GetPlexSync2XXResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPlexSync2XXResponse() *GetPlexSync2XXResponse {
	this := GetPlexSync2XXResponse{}
	return &this
}

// NewGetPlexSync2XXResponseWithDefaults instantiates a new GetPlexSync2XXResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPlexSync2XXResponseWithDefaults() *GetPlexSync2XXResponse {
	this := GetPlexSync2XXResponse{}
	return &this
}

// GetRunning returns the Running field value if set, zero value otherwise.
func (o *GetPlexSync2XXResponse) GetRunning() bool {
	if o == nil || IsNil(o.Running) {
		var ret bool
		return ret
	}
	return *o.Running
}

// GetRunningOk returns a tuple with the Running field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlexSync2XXResponse) GetRunningOk() (*bool, bool) {
	if o == nil || IsNil(o.Running) {
		return nil, false
	}
	return o.Running, true
}

// HasRunning returns a boolean if a field has been set.
func (o *GetPlexSync2XXResponse) HasRunning() bool {
	if o != nil && !IsNil(o.Running) {
		return true
	}

	return false
}

// SetRunning gets a reference to the given bool and assigns it to the Running field.
func (o *GetPlexSync2XXResponse) SetRunning(v bool) {
	o.Running = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise.
func (o *GetPlexSync2XXResponse) GetProgress() float32 {
	if o == nil || IsNil(o.Progress) {
		var ret float32
		return ret
	}
	return *o.Progress
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlexSync2XXResponse) GetProgressOk() (*float32, bool) {
	if o == nil || IsNil(o.Progress) {
		return nil, false
	}
	return o.Progress, true
}

// HasProgress returns a boolean if a field has been set.
func (o *GetPlexSync2XXResponse) HasProgress() bool {
	if o != nil && !IsNil(o.Progress) {
		return true
	}

	return false
}

// SetProgress gets a reference to the given float32 and assigns it to the Progress field.
func (o *GetPlexSync2XXResponse) SetProgress(v float32) {
	o.Progress = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetPlexSync2XXResponse) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlexSync2XXResponse) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetPlexSync2XXResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *GetPlexSync2XXResponse) SetTotal(v float32) {
	o.Total = &v
}

// GetCurrentLibrary returns the CurrentLibrary field value if set, zero value otherwise.
func (o *GetPlexSync2XXResponse) GetCurrentLibrary() PlexLibrary {
	if o == nil || IsNil(o.CurrentLibrary) {
		var ret PlexLibrary
		return ret
	}
	return *o.CurrentLibrary
}

// GetCurrentLibraryOk returns a tuple with the CurrentLibrary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlexSync2XXResponse) GetCurrentLibraryOk() (*PlexLibrary, bool) {
	if o == nil || IsNil(o.CurrentLibrary) {
		return nil, false
	}
	return o.CurrentLibrary, true
}

// HasCurrentLibrary returns a boolean if a field has been set.
func (o *GetPlexSync2XXResponse) HasCurrentLibrary() bool {
	if o != nil && !IsNil(o.CurrentLibrary) {
		return true
	}

	return false
}

// SetCurrentLibrary gets a reference to the given PlexLibrary and assigns it to the CurrentLibrary field.
func (o *GetPlexSync2XXResponse) SetCurrentLibrary(v PlexLibrary) {
	o.CurrentLibrary = &v
}

// GetLibraries returns the Libraries field value if set, zero value otherwise.
func (o *GetPlexSync2XXResponse) GetLibraries() []PlexLibrary {
	if o == nil || IsNil(o.Libraries) {
		var ret []PlexLibrary
		return ret
	}
	return o.Libraries
}

// GetLibrariesOk returns a tuple with the Libraries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlexSync2XXResponse) GetLibrariesOk() ([]PlexLibrary, bool) {
	if o == nil || IsNil(o.Libraries) {
		return nil, false
	}
	return o.Libraries, true
}

// HasLibraries returns a boolean if a field has been set.
func (o *GetPlexSync2XXResponse) HasLibraries() bool {
	if o != nil && !IsNil(o.Libraries) {
		return true
	}

	return false
}

// SetLibraries gets a reference to the given []PlexLibrary and assigns it to the Libraries field.
func (o *GetPlexSync2XXResponse) SetLibraries(v []PlexLibrary) {
	o.Libraries = v
}

func (o GetPlexSync2XXResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPlexSync2XXResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Running) {
		toSerialize["running"] = o.Running
	}
	if !IsNil(o.Progress) {
		toSerialize["progress"] = o.Progress
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.CurrentLibrary) {
		toSerialize["currentLibrary"] = o.CurrentLibrary
	}
	if !IsNil(o.Libraries) {
		toSerialize["libraries"] = o.Libraries
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetPlexSync2XXResponse) UnmarshalJSON(data []byte) (err error) {
	varGetPlexSync2XXResponse := _GetPlexSync2XXResponse{}

	err = json.Unmarshal(data, &varGetPlexSync2XXResponse)

	if err != nil {
		return err
	}

	*o = GetPlexSync2XXResponse(varGetPlexSync2XXResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "running")
		delete(additionalProperties, "progress")
		delete(additionalProperties, "total")
		delete(additionalProperties, "currentLibrary")
		delete(additionalProperties, "libraries")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetPlexSync2XXResponse struct {
	value *GetPlexSync2XXResponse
	isSet bool
}

func (v NullableGetPlexSync2XXResponse) Get() *GetPlexSync2XXResponse {
	return v.value
}

func (v *NullableGetPlexSync2XXResponse) Set(val *GetPlexSync2XXResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPlexSync2XXResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPlexSync2XXResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPlexSync2XXResponse(val *GetPlexSync2XXResponse) *NullableGetPlexSync2XXResponse {
	return &NullableGetPlexSync2XXResponse{value: val, isSet: true}
}

func (v NullableGetPlexSync2XXResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPlexSync2XXResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


