/*
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 

API version: v1.33.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package overseerr

import (
	"encoding/json"
)

// CreateDiscoverAddRequest struct for CreateDiscoverAddRequest
type CreateDiscoverAddRequest struct {
	Title *string `json:"title,omitempty"`
	Type *float32 `json:"type,omitempty"`
	Data *string `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateDiscoverAddRequest CreateDiscoverAddRequest

// NewCreateDiscoverAddRequest instantiates a new CreateDiscoverAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDiscoverAddRequest() *CreateDiscoverAddRequest {
	this := CreateDiscoverAddRequest{}
	return &this
}

// NewCreateDiscoverAddRequestWithDefaults instantiates a new CreateDiscoverAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDiscoverAddRequestWithDefaults() *CreateDiscoverAddRequest {
	this := CreateDiscoverAddRequest{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateDiscoverAddRequest) GetTitle() string {
	if o == nil || isNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDiscoverAddRequest) GetTitleOk() (*string, bool) {
	if o == nil || isNil(o.Title) {
    return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateDiscoverAddRequest) HasTitle() bool {
	if o != nil && !isNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateDiscoverAddRequest) SetTitle(v string) {
	o.Title = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateDiscoverAddRequest) GetType() float32 {
	if o == nil || isNil(o.Type) {
		var ret float32
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDiscoverAddRequest) GetTypeOk() (*float32, bool) {
	if o == nil || isNil(o.Type) {
    return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateDiscoverAddRequest) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given float32 and assigns it to the Type field.
func (o *CreateDiscoverAddRequest) SetType(v float32) {
	o.Type = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateDiscoverAddRequest) GetData() string {
	if o == nil || isNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDiscoverAddRequest) GetDataOk() (*string, bool) {
	if o == nil || isNil(o.Data) {
    return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateDiscoverAddRequest) HasData() bool {
	if o != nil && !isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *CreateDiscoverAddRequest) SetData(v string) {
	o.Data = &v
}

func (o CreateDiscoverAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !isNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *CreateDiscoverAddRequest) UnmarshalJSON(bytes []byte) (err error) {
	varCreateDiscoverAddRequest := _CreateDiscoverAddRequest{}

	if err = json.Unmarshal(bytes, &varCreateDiscoverAddRequest); err == nil {
		*o = CreateDiscoverAddRequest(varCreateDiscoverAddRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "title")
		delete(additionalProperties, "type")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateDiscoverAddRequest struct {
	value *CreateDiscoverAddRequest
	isSet bool
}

func (v NullableCreateDiscoverAddRequest) Get() *CreateDiscoverAddRequest {
	return v.value
}

func (v *NullableCreateDiscoverAddRequest) Set(val *CreateDiscoverAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDiscoverAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDiscoverAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDiscoverAddRequest(val *CreateDiscoverAddRequest) *NullableCreateDiscoverAddRequest {
	return &NullableCreateDiscoverAddRequest{value: val, isSet: true}
}

func (v NullableCreateDiscoverAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDiscoverAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


